<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    { {
            $skills = [
                'Arabic',
                'Laravel',
                'Voice Over',
                'Graphic Design',
                'AI Service',
                'Emerging Technologies',
                'PHP',
                'JavaScript',
                'Python',
                'Java',
                'C++',
                'C#',
                'Ruby',
                'Swift',
                'Kotlin',
                'HTML',
                'CSS',
                'SQL',
                'NoSQL',
                'React',
                'Vue.js',
                'Angular',
                'Django',
                'Flask',
                'Spring',
                'Machine Learning',
                'Data Analysis',
                'Data Science',
                'Cyber Security',
                'Blockchain',
                'DevOps',
                'Cloud Computing',
                'AWS',
                'Azure',
                'Google Cloud',
                'Docker',
                'Kubernetes',
                'Microservices',
                'Restful API',
                'GraphQL',
                'Mobile Development',
                'iOS Development',
                'Android Development',
                'Game Development',
                'Unity',
                'Unreal Engine',
                'Augmented Reality',
                'Virtual Reality',
                'UI/UX Design',
                'Project Management',
                'Agile Methodology',
                'Scrum',
                'Content Writing',
                'Copywriting',
                'SEO',
                'Digital Marketing',
                'Social Media Management',
                'Email Marketing',
                'Affiliate Marketing',
                'Sales',
                'Customer Service',
                'Technical Support',
                'IT Support',
                'Network Administration',
                'System Administration',
                'Database Administration',
                'Data Entry',
                'Transcription',
                'Translation',
                'Video Editing',
                'Audio Editing',
                'Photography',
                'Videography',
                '3D Modeling',
                '3D Animation',
                '2D Animation',
                'Illustration',
                'Web Design',
                'Web Development',
                'E-commerce',
                'Shopify',
                'WooCommerce',
                'Magento',
                'BigCommerce',
                'Prestashop',
                'Data Mining',
                'Business Analysis',
                'Market Research',
                'Financial Analysis',
                'Accounting',
                'Bookkeeping',
                'Human Resources',
                'Legal Consulting',
                'Business Consulting',
                'Startup Consulting',
                'Career Coaching',
                'Life Coaching',
                'Fitness Coaching',
                'Nutrition Coaching',
                'Music Production',
                'Sound Design',
                'Voice Acting',
                'Event Planning',
                'Travel Planning',
                'Interior Design',
                'Architecture',
                'Voice Over',
                'Music Production',
                'Sound Design',
                'Audio Editing',
                'Web Development', 'Front-End Development', 'Back-End Development', 'Full-Stack Development',
                'JavaScript Frameworks', 'React.js', 'Vue.js', 'Angular.js', 'Node.js', 'Express.js',
                'PHP Frameworks', 'Laravel', 'Symfony', 'CodeIgniter', 'CakePHP', 'Yii',
                'Python Frameworks', 'Flask', 'Django', 'Pyramid', 'Tornado', 'CherryPy',
                'Ruby on Rails', 'Sinatra', 'Hanami', 'Grape',
                'Java Frameworks', 'Spring Framework', 'Hibernate', 'JavaServer Faces', 'Grails',
                'C# Frameworks', '.NET Framework', '.NET Core', 'ASP.NET', 'Blazor', 'Entity Framework',
                'Mobile Development', 'iOS Development', 'Swift', 'Objective-C',
                'Android Development', 'Java', 'Kotlin',
                'Cross-Platform Development', 'Flutter', 'React Native', 'Ionic', 'Xamarin',
                'Game Development', 'Unity 3D', 'Unreal Engine', 'Godot', 'Cocos2d', 'CryEngine',
                'Database Management', 'SQL', 'MySQL', 'PostgreSQL', 'SQLite', 'Oracle Database', 'MongoDB',
                'NoSQL Databases', 'Cassandra', 'Redis', 'CouchDB', 'Firebase',
                'DevOps', 'Docker', 'Kubernetes', 'CI/CD', 'Jenkins', 'Travis CI', 'CircleCI', 'Ansible',
                'Puppet', 'Chef', 'Terraform', 'Vagrant', 'AWS', 'Azure', 'Google Cloud Platform',
                'Cloud Architecture', 'Microservices', 'Serverless Architecture',
                'APIs', 'RESTful APIs', 'GraphQL', 'SOAP', 'gRPC',
                'Security', 'Cybersecurity', 'Ethical Hacking', 'Penetration Testing',
                'OWASP', 'Encryption', 'Network Security', 'Security Auditing', 'Compliance',
                'Blockchain Development', 'Smart Contracts', 'Solidity', 'Hyperledger',
                'Crypto Development', 'Decentralized Applications', 'Web3 Development',
                'Artificial Intelligence', 'Machine Learning', 'Deep Learning', 'Natural Language Processing',
                'Computer Vision', 'TensorFlow', 'PyTorch', 'Keras', 'Scikit-Learn',
                'Data Science', 'Data Analysis', 'Data Mining', 'Big Data', 'Hadoop', 'Apache Spark',
                'Data Warehousing', 'ETL', 'Business Intelligence', 'Power BI', 'Tableau',
                'Data Visualization', 'Matplotlib', 'Seaborn', 'D3.js',
                'Statistics', 'R Programming', 'SAS', 'SPSS',
                'Bioinformatics', 'Genomics', 'Proteomics',
                'Health Informatics', 'Medical Imaging',
                'Digital Marketing', 'SEO', 'Content Marketing', 'Social Media Marketing',
                'Email Marketing', 'Affiliate Marketing', 'PPC Advertising', 'Google Ads',
                'Facebook Ads', 'LinkedIn Ads', 'Instagram Marketing',
                'E-commerce', 'Shopify', 'WooCommerce', 'Magento', 'BigCommerce',
                'Content Creation', 'Blogging', 'Podcasting', 'Vlogging',
                'Graphic Design', 'UI/UX Design', 'Adobe Photoshop', 'Adobe Illustrator',
                'Sketch', 'Figma', 'InVision', 'Adobe XD',
                'Video Editing', 'Adobe Premiere Pro', 'Final Cut Pro', 'DaVinci Resolve',
                'Motion Graphics', 'Adobe After Effects', 'Cinema 4D',
                '3D Modeling', 'Blender', 'Maya', 'ZBrush',
                'Game Design', 'Level Design', 'Character Design',
                'Music Production', 'Sound Engineering', 'Mixing and Mastering',
                'Podcast Editing', 'Voice Acting',
                'Business Management', 'Project Management', 'Agile Methodology', 'Scrum',
                'Kanban', 'Lean Management', 'Six Sigma', 'Change Management',
                'Financial Management', 'Accounting', 'Bookkeeping', 'Tax Preparation',
                'Financial Analysis', 'Investment Analysis',
                'Human Resources', 'Recruitment', 'Employee Relations', 'Payroll Management',
                'Performance Management', 'Training and Development',
                'Legal Consulting', 'Contract Law', 'Intellectual Property', 'Corporate Law',
                'Business Strategy', 'Startup Consulting', 'Business Planning',
                'Operations Management', 'Supply Chain Management',
                'Customer Service', 'Technical Support', 'Help Desk Support',
                'Sales', 'B2B Sales', 'B2C Sales', 'Salesforce CRM',
                'Real Estate', 'Property Management', 'Property Appraisal',
                'Event Planning', 'Wedding Planning', 'Corporate Event Planning',
                'Travel Planning', 'Tourism Management', 'Hospitality Management',
                'Interior Design', 'Architecture', 'Urban Planning',
                'Fitness Training', 'Nutrition Coaching', 'Wellness Coaching',
                'Yoga Instruction', 'Pilates Instruction',
                'Languages', 'Translation', 'Interpretation',
                'Technical Writing', 'Creative Writing', 'Copywriting',
                'Photography', 'Videography',
                'Public Speaking', 'Presentation Skills',
                'Leadership', 'Team Management', 'Conflict Resolution',
                'Personal Development', 'Time Management', 'Stress Management',
                'Education', 'Teaching', 'Tutoring',
                'Research', 'Academic Research', 'Market Research',
                'Library Science', 'Information Science',
                'Data Entry', 'Transcription',
                'Administration', 'Office Management',
                'Virtual Assistance', 'Executive Assistance',
                'Product Management', 'Product Design', 'Product Strategy',
                'Quality Assurance', 'Testing', 'Software Testing',
                'User Testing', 'A/B Testing', 'Usability Testing',
                'Network Engineering', 'System Administration', 'Linux Administration',
                'Windows Administration', 'MacOS Administration',
                'IT Support', 'Technical Support',
                'Network Security', 'System Security', 'Penetration Testing',
                'Firewalls', 'VPN', 'Proxy Servers',
                'Telecommunications', 'VoIP', 'Unified Communications',
                'Hardware Design', 'Embedded Systems', 'IoT Development',
                'Robotics', 'Automation', 'Mechatronics',
                'Renewable Energy', 'Solar Energy', 'Wind Energy',
                'Environmental Science', 'Climate Change', 'Sustainability',
                'Agriculture', 'Farming', 'Permaculture',
                'Food Science', 'Nutrition', 'Dietetics',
                'Healthcare', 'Nursing', 'Medical Assistance',
                'Emergency Medicine', 'Surgery',
                'Mental Health', 'Counseling', 'Psychotherapy',
                'Social Work', 'Community Development',
                'Political Science', 'International Relations',
                'Public Administration', 'Government Policy',
                'Law Enforcement', 'Criminal Justice',
                'Military Science', 'Defense Studies',
                'Anthropology', 'Sociology', 'Cultural Studies',
                'Philosophy', 'Ethics',
                'Religion', 'Theology', 'Spirituality',
                'History', 'Archaeology',
                'Geography', 'Geology', 'Geospatial Analysis',
                'Astronomy', 'Astrophysics',
                'Physics', 'Quantum Mechanics', 'Thermodynamics',
                'Chemistry', 'Biochemistry', 'Organic Chemistry',
                'Biology', 'Genetics', 'Ecology',
                'Mathematics', 'Calculus', 'Algebra', 'Statistics',
                'Economics', 'Microeconomics', 'Macroeconomics',
                'Finance', 'Corporate Finance', 'Personal Finance',
                'Insurance', 'Risk Management',
                'Marketing', 'Brand Management', 'Product Marketing',
                'Public Relations', 'Media Relations',
                'Supply Chain', 'Logistics', 'Procurement',
                'Manufacturing', 'Production Planning',
                'Quality Control', 'Lean Manufacturing',
                'Automotive Engineering', 'Mechanical Engineering',
                'Electrical Engineering',

            ];

            foreach ($skills as $skill) {
                DB::table('skills')->insert([
                    'name' => $skill,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
